-- CREATE USER 'beneficiary'@'%' IDENTIFIED BY 'Beneficiary@2019';
GRANT ALL PRIVILEGES ON BENEFICIARY_DB.* TO 'beneficiary'@'%';
FLUSH PRIVILEGES;

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BENEFICIARY_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BENEFICIARY_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BENEFICIARY_DB` DEFAULT CHARACTER SET latin1 ;
USE `BENEFICIARY_DB` ;

-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`TOKEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`TOKEN` (
  `TOKEN_ID` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `TOKEN_KEY` VARCHAR(255) NOT NULL,
  `SYSTEM_NAME` VARCHAR(45) NOT NULL,
  `TOKEN_EXP` DATE NOT NULL,
  `UPDATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(45) NULL,
  PRIMARY KEY (`TOKEN_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `SYSTEM_UNIQUE` ON `BENEFICIARY_DB`.`TOKEN` (`SYSTEM_NAME` ASC);


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`COMPANY_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`COMPANY_MASTER` (
  `COMPANY_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` VARCHAR(100) NOT NULL,
  `WEB_URL` VARCHAR(50) NULL,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`COMPANY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`SERVICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`SERVICES` (
  `SERVICE_ID` INT UNSIGNED NOT NULL,
  `COMPANY_ID` INT UNSIGNED NOT NULL,
  `CREDIT_ACCOUNT_NUM` VARCHAR(30) NULL,
  `SERVICE_CODE` VARCHAR(45) NOT NULL,
  `SERVICE_NAME` VARCHAR(65) NOT NULL,
  `MIN_PAY_AMOUNT` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `MAX_PAY_AMOUNT` INT UNSIGNED NULL,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `IS_ACTIVE` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `PRD` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  UNIQUE INDEX `COMPANY_SERVICE_CODE_UNIQUE` (`COMPANY_ID` ASC, `SERVICE_CODE` ASC),
  CONSTRAINT `fk_COMPANY`
    FOREIGN KEY (`COMPANY_ID`)
    REFERENCES `BENEFICIARY_DB`.`COMPANY_MASTER` (`COMPANY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`SYSTEM_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`SYSTEM_MASTER` (
  `SYSTEM_ID` SMALLINT UNSIGNED NOT NULL,
  `SYSTEM_NAME` VARCHAR(20) NOT NULL,
  `SYSTEM_DESC` VARCHAR(100) NULL,
  `IS_ACTIVE` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SYSTEM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER` (
  `CONSUMER_TYPE_ID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CONSUMER_TYPE_NAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`CONSUMER_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (
  `BEN_TYPE_ID` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BEN_TYPE` VARCHAR(100) NULL,
  PRIMARY KEY (`BEN_TYPE_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `BEN_TYPE_UNIQUE` ON `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE` ASC);


-- -----------------------------------------------------
-- Table `BENEFICIARY_DB`.`BENEFICIARIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BENEFICIARY_DB`.`BENEFICIARIES` (
  `BENEFICIARY_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BEN_TYPE_ID` TINYINT UNSIGNED NOT NULL,
  `CIF` VARCHAR(10) NOT NULL,
  `BEN_ALIAS_NAME` VARCHAR(45) NOT NULL,
  `BEN_SWIFT` VARCHAR(12) NULL,
  `BEN_ACCOUNT_NUM` VARCHAR(35) NULL,
  `BEN_FIRST_NAME` VARCHAR(100) NULL,
  `BEN_LAST_NAME` VARCHAR(100) NULL,
  `BEN_ADDRESS_1` VARCHAR(100) NULL,
  `BEN_ADDRESS_2` VARCHAR(100) NULL,
  `BEN_ADDRESS_3` VARCHAR(100) NULL,
  `BEN_CURRENCY` VARCHAR(4) NULL,
  `CONSUMER_NUM` VARCHAR(30) NULL,
  `CONSUMER_TYPE_ID` TINYINT UNSIGNED NULL,
  `SERVICE_ID` INT UNSIGNED NULL,
  `IS_ACTIVE` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `RESERVE` VARCHAR(255) NULL,
  `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` SMALLINT UNSIGNED NOT NULL,
  `UPDATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`BENEFICIARY_ID`),
  CONSTRAINT `fk_SERVICE_ID`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `BENEFICIARY_DB`.`SERVICES` (`SERVICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CREATOR`
    FOREIGN KEY (`CREATED_BY`)
    REFERENCES `BENEFICIARY_DB`.`SYSTEM_MASTER` (`SYSTEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UPDATOR`
    FOREIGN KEY (`UPDATED_BY`)
    REFERENCES `BENEFICIARY_DB`.`SYSTEM_MASTER` (`SYSTEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSUMER_TYPE_ID`
    FOREIGN KEY (`CONSUMER_TYPE_ID`)
    REFERENCES `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER` (`CONSUMER_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BEN_TYPE_ID`
    FOREIGN KEY (`BEN_TYPE_ID`)
    REFERENCES `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `BENEFICIARY_UNIQUE` ON `BENEFICIARY_DB`.`BENEFICIARIES` (`CIF` ASC, `BEN_ALIAS_NAME` ASC) ;

CREATE INDEX `fk_CREATOR_idx` ON `BENEFICIARY_DB`.`BENEFICIARIES`(`CREATED_BY` ASC);

CREATE INDEX `fk_SERVICE_ID_idx` ON `BENEFICIARY_DB`.`BENEFICIARIES`(`SERVICE_ID` ASC);

CREATE INDEX `fk_CONSUMER_TYPE_ID_idx` ON `BENEFICIARY_DB`.`BENEFICIARIES`(`CONSUMER_TYPE_ID` ASC);

CREATE INDEX `fk_BEN_TYPE_ID_idx` ON `BENEFICIARY_DB`.`BENEFICIARIES`(`BEN_TYPE_ID` ASC);

CREATE INDEX `fk_UPDATOR_idx` ON `BENEFICIARY_DB`.`BENEFICIARIES`(`UPDATED_BY` ASC);

CREATE UNIQUE INDEX `ACCOUNT_UNIQUE` ON `BENEFICIARY_DB`.`BENEFICIARIES` (`CIF` ASC, `BEN_ACCOUNT_NUM` ASC);

CREATE UNIQUE INDEX `SERVICE_UNIQUE` ON `BENEFICIARY_DB`.`BENEFICIARIES` (`CIF` ASC, `CONSUMER_TYPE_ID` ASC, `SERVICE_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BENEFICIARY_DB`.`COMPANY_MASTER`
-- -----------------------------------------------------
START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`COMPANY_MASTER` (`COMPANY_ID`, `COMPANY_NAME`, `WEB_URL`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`) VALUES (1, 'ONEIC', 'http://www.oneic.com.om', DEFAULT, DEFAULT, 1);
INSERT INTO `BENEFICIARY_DB`.`COMPANY_MASTER` (`COMPANY_ID`, `COMPANY_NAME`, `WEB_URL`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`) VALUES (2, 'OIFC', 'http://oifc.com', DEFAULT, DEFAULT, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BENEFICIARY_DB`.`SERVICES`
-- -----------------------------------------------------
START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`SERVICES` (`SERVICE_ID`, `COMPANY_ID`, `CREDIT_ACCOUNT_NUM`, `SERVICE_CODE`, `SERVICE_NAME`, `MIN_PAY_AMOUNT`, `MAX_PAY_AMOUNT`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`, `PRD`) VALUES (1, 1, '0002787', 'WATER', 'ONEIC Water', 1, 2000, DEFAULT, DEFAULT, 1, 'BPWT');
INSERT INTO `BENEFICIARY_DB`.`SERVICES` (`SERVICE_ID`, `COMPANY_ID`, `CREDIT_ACCOUNT_NUM`, `SERVICE_CODE`, `SERVICE_NAME`, `MIN_PAY_AMOUNT`, `MAX_PAY_AMOUNT`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`, `PRD`) VALUES (2, 1, '0002787', 'ELECTRICITY', 'ONEIC Electricity', 1, 2000, DEFAULT, DEFAULT, 1, 'BPEC');
INSERT INTO `BENEFICIARY_DB`.`SERVICES` (`SERVICE_ID`, `COMPANY_ID`, `CREDIT_ACCOUNT_NUM`, `SERVICE_CODE`, `SERVICE_NAME`, `MIN_PAY_AMOUNT`, `MAX_PAY_AMOUNT`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`, `PRD`) VALUES (3, 2, '0002789', 'WATER', 'OIFC Water', 1, 2000, DEFAULT, DEFAULT, 1, 'BPWT');
INSERT INTO `BENEFICIARY_DB`.`SERVICES` (`SERVICE_ID`, `COMPANY_ID`, `CREDIT_ACCOUNT_NUM`, `SERVICE_CODE`, `SERVICE_NAME`, `MIN_PAY_AMOUNT`, `MAX_PAY_AMOUNT`, `CREATED_ON`, `UPDATED_ON`, `IS_ACTIVE`, `PRD`) VALUES (4, 2, '0002789', 'ELECTRICITY', 'OIFC Electricity', 1, 2000, DEFAULT, DEFAULT, 1, 'BPEC');


COMMIT;


-- -----------------------------------------------------
-- Data for table `BENEFICIARY_DB`.`SYSTEM_MASTER`
-- -----------------------------------------------------
START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`SYSTEM_MASTER` (`SYSTEM_ID`, `SYSTEM_NAME`, `SYSTEM_DESC`, `IS_ACTIVE`, `CREATED_ON`, `UPDATED_ON`) VALUES (1, 'TEST', 'Testing system to be locked in production', DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER`
-- -----------------------------------------------------
START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER` (`CONSUMER_TYPE_ID`, `CONSUMER_TYPE_NAME`) VALUES (1, 'ACCOUNTNUMBER');
INSERT INTO `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER` (`CONSUMER_TYPE_ID`, `CONSUMER_TYPE_NAME`) VALUES (2, 'MOBILENUMBER');
INSERT INTO `BENEFICIARY_DB`.`CONSUMER_TYPE_MASTER` (`CONSUMER_TYPE_ID`, `CONSUMER_TYPE_NAME`) VALUES (3, 'CONSUMERNUMBER');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER`
-- -----------------------------------------------------
START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE_ID`, `BEN_TYPE`) VALUES (1, 'LOCAL_INTERNAL');
INSERT INTO `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE_ID`, `BEN_TYPE`) VALUES (2, 'LOCAL_EXTERNAL');
INSERT INTO `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE_ID`, `BEN_TYPE`) VALUES (3, 'INTERNATIONAL');
INSERT INTO `BENEFICIARY_DB`.`BENEFICIARY_TYPE_MASTER` (`BEN_TYPE_ID`, `BEN_TYPE`) VALUES (4, 'UTILITY');

COMMIT;

START TRANSACTION;
USE `BENEFICIARY_DB`;
INSERT INTO `BENEFICIARY_DB`.`TOKEN` (`TOKEN_KEY`, `SYSTEM_NAME`, `TOKEN_EXP`, `UPDATED_BY`) VALUES ('TESTKEY001', 'ONEIC', '2019-12-31', '1');

COMMIT;

-- START TRANSACTION;
-- USE BENEFICIARY_DB;
-- INSERT INTO `BENEFICIARY_DB`.`BENEFICIARIES` (`BEN_TYPE_ID`, `CIF`, `BEN_ALIAS_NAME`, `CONSUMER_NUM`, `CONSUMER_TYPE_ID`, `SERVICE_ID`, `CREATED_BY`, `UPDATED_BY`) VALUES ('4', '0000003', 'water', '91754379', '2', '1', '1', '1');
-- INSERT INTO `BENEFICIARY_DB`.`BENEFICIARIES` (`BEN_TYPE_ID`, `CIF`, `BEN_ALIAS_NAME`, `BEN_SWIFT`, `BEN_ACCOUNT_NUM`, `BEN_FIRST_NAME`, `BEN_LAST_NAME`, `BEN_ADDRESS_1`, `BEN_ADDRESS_2`, `BEN_ADDRESS_3`, `BEN_CURRENCY`, `CREATED_BY`, `UPDATED_BY`) VALUES ('3', '0000003', 'Revanth', 'SC00003456', '0192874689204', 'Revanth', 'Nemani', '18, 18 Villas', 'Madinat Al Ilam', 'Muscat', 'OMR', '1', '1');
-- COMMIT;
